// Shared by devotion and Bible-reflection generation. These are editorial
// instructions for generated prose; Bible-source quotations remain verbatim.
module.exports = [
  'Choose vocabulary by meaning and grammatical role, not by replacing every similar word. Grace is nåde / فضل; mercy is barmhjertighed / رحم or رحمت; redemption is forløsning / مخلصی; atonement is soning / کفارہ. Do not collapse these distinct concepts.',
  'Preserve accepted Christian synonyms such as Saviour/Savior, Holy Communion/the Lord’s Supper, and church/congregation when appropriate. Distinguish the church as a community from a church building. Do not impose a denominational interpretation that is absent from the passage.',
  'Do not add our, my, or your to a divine title unless the source expresses that possession. Preserve direct address in prayers: Lord Jesus, help us / Herre Jesus, hjælp os / اے خداوند یسوع، ہماری مدد کر۔',
  'Write coherent short sentences with clear subjects and natural transitions. Preserve cause, contrast, conditions, and commands. Avoid fragments, repetitive openings, literal idiom translations, and unnecessary ornate vocabulary. Keep questions as questions.',
  'In Danish use tro på Gud, bede til Gud, omvende sig, tilgive nogen, and følge Jesus with the correct prepositions and inflections. In English use believe in, pray to, repent of, and forgive someone. In Urdu use خدا پر ایمان رکھنا، خدا سے دعا کرنا، گناہوں سے توبہ کرنا، and یسوع کی پیروی کرنا when appropriate.',
  'Keep resurrection distinct from the day of judgment: use مردوں میں سے جی اٹھنا for rising from the dead where this clarifies the meaning, and عدالت کا دن for the day of judgment. Do not translate every occurrence of قیامت into the same English or Danish term without context.',
  'Write idiomatic, grammatically complete English, Danish, and Christian Urdu. Preserve the same meaning, tense, negation, speaker, and recipients in every language.',
  'Resolve pronouns from the whole sentence and surrounding context. Urdu وہ، انہوں نے، انہیں، ان کا can respectfully refer to one person. When they refer to Jesus Christ, translate with he/him/his in English and han/ham/hans in Danish, not they/them/their or de/dem/deres. Keep genuine groups plural.',
  'Track subjects and objects separately: Jesus gives them salvation keeps them plural when referring to people. When two people or groups are mentioned, repeat the appropriate name if needed for clarity rather than guessing a pronoun.',
  'English example: Jesus Christ wants us to change our lives and give our lives to Him. Danish: Jesus Kristus ønsker, at vi ændrer vores liv og overgiver vores liv til ham. Urdu: یسوع مسیح چاہتے ہیں کہ ہم اپنی زندگیاں بدلیں اور اپنی زندگیاں اُن کے سپرد کریں۔',
  'Use correct English subject-verb agreement (He wants, He gives, they want, they give); preserve past tense and modal verbs. Distinguish our lives from my life according to the intended meaning.',
  'Use natural Danish word order and inflection. Distinguish han/ham/hans and hun/hende/hendes; use sin/sit/sine only for possession by the grammatical subject where Danish grammar requires it. Use du/dig/din in direct prayer to God, preserving the speaker and addressee.',
  'In Urdu, use natural Christian phrasing and consistent respectful agreement for Jesus (یسوع مسیح چاہتے ہیں، وہ فرماتے ہیں). Distinguish ہم، ہمیں، ہمارا from وہ، انہیں، ان کا. Match gender and number to the relevant noun; avoid literal English word order.',
  'Use context-appropriate vocabulary: repentance / omvendelse / توبہ; forgiveness / tilgivelse / معافی; grace / nåde / فضل; salvation / frelse / نجات; eternal life / evigt liv / ابدی زندگی; resurrection / opstandelse / قیامت. Preserve distinctions between these concepts.',
  'Use surrender our lives to Christ / overgive vores liv til Kristus / اپنی زندگیاں مسیح کے سپرد کرنا and walk in faith / vandre i tro / ایمان سے چلنا when those meanings are intended. Do not insert these expressions where the source means something else.',
  'Before returning, compare each translation with the English content and check every pronoun, subject, recipient, possessive, tense, and negation. Correct grammar without adding theological claims or changing Bible quotations or references.'
]
